services:
    mirakurun:
        image: mirakurun:4.0.0-beta.16.mod
        container_name: Mirakurun
        cap_add:
            - SYS_ADMIN
            - SYS_NICE
        ports:
            - "40772:40772"
            - "9229:9229"
        volumes:
            - ../Mirakurun/bind/run/:/var/run/
            - ../Mirakurun/bind/opt/:/opt/
            - ../Mirakurun/bind/config/:/app-config/
            - ../Mirakurun/bind/data/:/app-data/
            # ホストの pcscd を使う場合 (DISABLE_PCSCD=1)
            #- /var/run/pcscd/pcscd.comm:/var/run/pcscd/pcscd.comm
            # add all devices (for development purposes)
            # 全てのデバイスを追加 (開発用)
            #- /dev:/dev
        environment:
            TZ: "Asia/Tokyo"
            # pcscd を無効にする場合は "1"
            DISABLE_PCSCD: "${DISABLE_PCSCD:-1}"
            # B25 テストコマンドの取得とビルドを無効にする場合は "1"
            DISABLE_B25_TEST: "${DISABLE_B25_TEST:-1}"
            # `network_mode: host` をコメントアウトする場合はここもコメントアウト
            #DOCKER_NETWORK: host
            # ブラウザから IP アドレス以外でアクセスする場合はホスト名を設定
            #hostname: localhost
            # --
            # for debug
            #LOG_LEVEL: "3"
            #DEBUG: "true"

        # `devices` を全てコメントアウトした場合は `devices:` もコメントアウト
        devices:
            # カードリーダーを使う場合
            #- /dev/bus:/dev/bus
            # DVB チューナーを使う場合
            - /dev/dvb:/dev/dvb
            # KEIAN
            #- /dev/FSUSB2N_1:/dev/FSUSB2N_1
            #- /dev/FSUSB2N_2:/dev/FSUSB2N_2
            # SANPAKUN
            #- /dev/SANPAKUN_1:/dev/SANPAKUN_1
            #- /dev/SANPAKUN_2:/dev/SANPAKUN_2
            # pt1_drv
            #- /dev/pt1video0:/dev/pt1video0
            #- /dev/pt1video1:/dev/pt1video1
            #- /dev/pt1video2:/dev/pt1video2
            #- /dev/pt1video3:/dev/pt1video3
            # pt3_drv
            #- /dev/pt3video0:/dev/pt3video0
            #- /dev/pt3video1:/dev/pt3video1
            #- /dev/pt3video2:/dev/pt3video2
            #- /dev/pt3video3:/dev/pt3video3
#        restart: always
        logging:
            driver: json-file
            options:
                max-file: "1"
                max-size: 10m
        ipc: host

    mysql:
        image: mariadb:10.11.8.mod
        container_name: mariadb
        ports:
            - "7777:3306"
        volumes:
            - ../mariadb/db/mariadb_data:/var/lib/mysql
        environment:
            MYSQL_USER: epgstation
            MYSQL_PASSWORD: epgstation
            MYSQL_ROOT_PASSWORD: epgstation
            MYSQL_DATABASE: epgstation_db
            TZ: "Asia/Tokyo"
        command: --performance-schema=false --expire_logs_days=1 # for mariadb
        # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=false --expire_logs_days=1 # for mariadb
        # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_as_ci --performance-schema=false --expire_logs_days=1 --default-authentication-plugin=mysql_native_password # for myql
#        restart: always
        logging:
            options:
                max-size: "10m"
                max-file: "3"

    epgstation:
        image: epgstation:2.10.0
        container_name: EPGStation
        build:
            context: "./epgstation"
            dockerfile: "debian.Dockerfile"
        volumes:
            - ./epgstation/config:/app/config
            - ./epgstation/data:/app/data
            - ./epgstation/thumbnail:/app/thumbnail
            - /tmp/.cache/docker/EPGStation/logs:/app/logs
            - ./recorded:/app/recorded
        environment:
            TZ: "Asia/Tokyo"
        depends_on:
            - mirakurun
            - mysql
        ports:
            - "8888:8888"
            - "8889:8889"
#         user: "1000:1000"
#         devices:
#             - /dev/dri:/dev/dri
#        restart: always

volumes:
    mariadb_data:
        driver: local

