services:
  mirakurun:
    build:
      context: ../
      dockerfile: docker/Dockerfile_mirakurun
    image: mirakurun:3.9.0-rc.4.mod
    container_name: mirakurun
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    environment:
      TZ: Asia/Tokyo
      DOCKER_NETWORK: host
      # LOG_LEVEL: "3"
      # DEBUG: "true"
    network_mode: host
    devices:
      - /dev/bus:/dev/bus
      - /dev/FSUSB2N_1:/dev/FSUSB2N_1
      - /dev/FSUSB2N_2:/dev/FSUSB2N_2
      - /dev/SANPAKUN_1:/dev/SANPAKUN_1
      - /dev/SANPAKUN_2:/dev/SANPAKUN_2
    volumes:
      # ** CAUTION **
      # (default) `/usr/local/mirakurun/*` has been moved to `/opt/mirakurun/*`
      # try:
      #   sudo mv -vf /usr/local/mirakurun /opt/mirakurun
      #   sudo mkdir -p /opt/mirakurun/run /opt/mirakurun/opt /opt/mirakurun/config /opt/mirakurun/data
      # you can change to any location if required.
      - type: bind
        source: ../bind/run/
        target: /var/run/
      - type: bind
        source: ../bind/opt/
        target: /opt/
      - type: bind
        source: ../bind/config/
        target: /app-config/
      - type: bind
        source: ../bind/data/
        target: /app-data/
#    restart: always
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m
