ARG ARCH=
FROM ${ARCH}node:18.15.0-buster AS build
WORKDIR /app
ENV DOCKER=YES NODE_ENV=production
ADD . .
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends build-essential && \
    npm install --production=false && \
    npm run build && \
    npm install -g --unsafe-perm --production

FROM ${ARCH}node:18.15.0-buster-slim
WORKDIR /app
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        wget \
        p7zip-full \
        git \
        automake \
        autoconf \
        cmake \
        make \
        gcc \
        g++ \
        pkg-config \
        pcscd \
        libpcsclite-dev \
        libccid \
        libdvbv5-dev \
        pcsc-tools \
        dvb-tools \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY --from=build /usr/local/lib/node_modules/mirakurun /app

# イメージ作成時にホストからファイルをコピーする
#COPY ./tuner_app /opt/tuner_app
RUN mkdir /opt/TV_app && cd /opt/TV_app && \
    wget https://github.com/AngieKawai-4649/bondora_iroiro/releases/download/otanoshimi/otanoshimi_linux.7z && \
    7z x -pk-an\!\! otanoshimi_linux.7z && cd starbucks/src && make && make install && make clean && \
    cd /opt/TV_app && git clone https://github.com/AngieKawai-4649/libarib25.git && cd libarib25/src  && \
    make -f Make_lib && make -f Make_lib install && make -f Make_exe STARBUCKS=1 && make -f Make_exe STARBUCKS=1 install && make -f Make_lib clean && make -f Make_exe STARBUCKS=1 clean && \
    cd /opt/TV_app && git clone https://github.com/AngieKawai-4649/recfsusb2n.git && cd recfsusb2n/src && \
    make STARBUCKS=1  && make STARBUCKS=1 install && make STARBUCKS=1 clean && \
    cd /opt/TV_app && git clone https://github.com/AngieKawai-4649/recsanpakun.git && cd recsanpakun/src && \
    make STARBUCKS=1  && make STARBUCKS=1 install && make STARBUCKS=1 clean && \
    cd /opt/TV_app && git clone https://github.com/AngieKawai-4649/recdvb.git && cd recdvb/src && \
    make STARBUCKS=1  && make STARBUCKS=1 install && make STARBUCKS=1 clean && \
    cd /opt/TV_app && git clone https://github.com/stz2012/recpt1.git && \
    cd /opt/TV_app/recpt1/recpt1 && ./autogen.sh && ./configure --enable-b25 && \
    mv /opt/TV_app/starbucks/Makefile_starbucks /opt/TV_app/recpt1/recpt1/Makefile_starbucks && \
    cd /opt/TV_app/recpt1/recpt1 && make -f Makefile_starbucks && make -f Makefile_starbucks install && make -f Makefile_starbucks clean


CMD ["./docker/container-init.sh"]
EXPOSE 40772 9229
