# docker-compose.yml
version: '3'
services:
    mariadb:
        image: mariadb:10.11.8.mod
        container_name: mariadb
        ports:
            - "7777:3306"
        volumes:
            - ./db/mariadb_data:/var/lib/mysql
#        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: "Asia/Tokyo"
#        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=false --expire_logs_days=1 # for mariadb
volumes:
    mariadb_data:
        driver: local
