ARG ARCH=
FROM ${ARCH}node:22.14.0-bookworm AS build
WORKDIR /app
ENV DOCKER=YES NODE_ENV=production
ADD . .
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends build-essential && \
    npm ci --include=dev && \
    npm run build && \
    npm ci --omit=dev

FROM ${ARCH}node:22.14.0-bookworm-slim
WORKDIR /app
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        wget \
        p7zip-full \
        git \
        make \
        gcc \
        g++ \
        pkg-config \
        pcscd \
        libpcsclite-dev \
        libccid \
        libdvbv5-dev \
        pcsc-tools \
        dvb-tools \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY --from=build /app /app

# イメージ作成時にホストからファイルをコピーする
#COPY ./tuner_app /opt/tuner_app
SHELL ["/bin/bash", "-c"]
RUN mkdir -p /usr/local/lib/pkgconfig && \
    export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig && \
    mkdir /opt/TV_app && cd /opt/TV_app && \
    wget https://github.com/AngieKawai-4649/bondora_iroiro/releases/download/otanoshimi/otanoshimi_linux.7z && \
    7z x -pk-an\!\! otanoshimi_linux.7z && pushd starbucks/src && make && make install && make clean && popd && \
    git clone https://github.com/AngieKawai-4649/channelconf.git && pushd channelconf/src  && \
    make && make install && make clean && popd && \
    git clone https://github.com/AngieKawai-4649/libarib25.git && pushd libarib25/src  && \
    make -f Make_lib && make -f Make_lib install && make -f Make_exe STARBUCKS=1 && make -f Make_exe STARBUCKS=1 install && make -f Make_lib clean && make -f Make_exe STARBUCKS=1 clean && popd && \
    git clone https://github.com/AngieKawai-4649/recfsusb2n.git && pushd recfsusb2n/src && \
    make STARBUCKS=1  && make STARBUCKS=1 install && make STARBUCKS=1 clean && popd && \
    git clone https://github.com/AngieKawai-4649/recsanpakun.git && pushd recsanpakun/src && \
    make STARBUCKS=1  && make STARBUCKS=1 install && make STARBUCKS=1 clean && popd && \
    git clone https://github.com/AngieKawai-4649/recdvb.git && pushd recdvb/src && \
    make STARBUCKS=1  && make STARBUCKS=1 install && make STARBUCKS=1 clean && popd && \
    git clone https://github.com/AngieKawai-4649/recpt1.git && pushd recpt1/recpt1 && \
    make STARBUCKS=1 && make STARBUCKS=1 install && make STARBUCKS=1 clean && popd


CMD ["./docker/container-init.sh"]
EXPOSE 40772 9229
