- name: PT2-S1
  types:
    - BS
    - CS
  command: recdvb --dev 0 --b25 <channel> - -
  decoder: 
  isDisabled: false

- name: PT2-S2
  types:
    - BS
    - CS
  command: recdvb --dev 1 --b25 <channel> - -
  decoder: 
  isDisabled: false

- name: PT2-T1
  types:
    - GR
  command: recdvb --dev 2 --b25 <channel> - -
  decoder: 
  isDisabled: false

- name: PT2-T2
  types:
    - GR
  command: recdvb --dev 3 --b25 <channel> - -
  decoder: 
  isDisabled: false

- name: PT3-S1
  types:
    - BS
    - CS
  command: recdvb --dev 4 --b25 <channel> - -
  decoder: 
  isDisabled: false

- name: PT3-S2
  types:
    - BS
    - CS
  command: recdvb --dev 5 --b25 <channel> - -
  decoder: 
  isDisabled: false

- name: PT3-T1
  types:
    - GR
  command: recdvb --dev 6 --b25 <channel> - -
  decoder: 
  isDisabled: false

- name: PT3-T2
  types:
    - GR
  command: recdvb --dev 7 --b25 <channel> - -
  decoder: 
  isDisabled: false

- name: FSUSB2N-T1
  types:
    - GR
  command: recfsusb2n --b25 --dev /dev/FSUSB2N_1 <channel> - -
  decoder: 
  isDisabled: true

- name: FSUSB2N-T2
  types:
    - GR
  command: recfsusb2n --b25 --dev /dev/FSUSB2N_2 <channel> - -
  decoder: 
  isDisabled: true

- name: SANPAKUN-ST1
  types:
    - BS
    - CS
  command: recsanpakun --b25 --dev /dev/SANPAKUN_1 <channel> - -
  decoder: 
  isDisabled: true

- name: SANPAKUN-ST2
  types:
    - BS
    - CS
  command: recsanpakun --b25 --dev /dev/SANPAKUN_2 <channel> - -
  decoder: 
  isDisabled: true


- name: TBS6922
  types:
    - SKY
  command: szap-s2j -c /usr/local/etc/szap-s2j.conf -l <satelite> -S 1 -p -r -M 5 -C 35 <channel>
  dvbDevicePath: /dev/dvb/adapter0/dvr0
  decoder: arib-b1-stream-test
  isDisabled: true
